"""initial

Revision ID: 6481858fad52
Revises: 1f268e6bf748
Create Date: 2024-09-16 19:49:51.956810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6481858fad52'
down_revision: Union[str, None] = '1f268e6bf748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_call',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('send_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('firstname_and_surname', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=False),
    sa.Column('organization', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_request')
    op.drop_table('order_call')
    # ### end Alembic commands ###
