"""initial

Revision ID: d5ce21663839
Revises: 3082dcbac161
Create Date: 2024-09-22 12:03:40.748595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ce21663839'
down_revision: Union[str, None] = '3082dcbac161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
