version: "3.8"
services:
  db:
    image: postgres:15
    container_name: uralpromcentr_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - 5432:5432

  uralpromcenter_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uralpromcenter_app
    env_file:
      - .env.docker
    depends_on:
      - db
    command: sh -c "sleep 10 && alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000


volumes:
  postgresdata: