version: "3.8"
services:
  db:
    image: postgres:15
    container_name: ask-bp_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - 5432:5432

  ask-bp_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ask-bp_app
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
    command: sh -c "sleep 10 && alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

  redis:
    image: redis:7
    container_name: ask-bp_redis
    ports:
      - 6379:6379

  celery:
    image: ask-bp_celery
    build:
      context: .
    container_name: ask-bp_celery
    command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO"
    env_file:
      - .env.docker
    depends_on:
      - redis


volumes:
  postgresdata:
  grafanadata:
  prometheusdata: